---
- name: Playbook para instalar o apache!!
  hosts: web
  become: yes
  tasks:
  - name: Instalar o apache pelo yum 
    yum:
      name: httpd
      state: latest
  - name: Iniciando o Apache!
  service:
      name: httpd 
      state: started
